version: '3'
services:
  db:
    image: mariadb:10.3
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    restart: always
  drupal:
    depends_on:
      - db
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
    restart: always
  solr:
    image: solr:8
    ports:
      - "8983:8983"
    volumes:
      - ./mycores/collection1:/mycores/collection1
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - collection1
      - /mycores/collection1
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
volumes:
  db_data: